spring:
  application:
    name: account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

  jpa:
    properties:
      hibernate:
        default_schema: account_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      default-schema: account_schema
  liquibase:
    enabled: true
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5432/bank}
    user: postgres
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    change-log: classpath:db/changelog/changelog.yml

management:
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8090