replicaCount: 1

image:
  repository: account
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

# Подождать, пока Postgres и Keycloak будут готовы
initContainers:
  - name: wait-for-postgresql
    image: busybox:1.36
    command:
      - sh
      - -c
      - |
        until nc -z umbrella-chart-postgresql 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 3
        done
  - name: wait-for-keycloak
    image: busybox:1.36
    command:
      - sh
      - -c
      - |
        until nc -z umbrella-chart-keycloak 8080; do
          echo "Waiting for Keycloak..."
          sleep 3
        done

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8090
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8090
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false

env:
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://umbrella-chart-postgresql:5432/bank
  - name: SPRING_DATASOURCE_USERNAME
    value: postgres
  - name: SPRING_DATASOURCE_PASSWORD
    value: admin
  - name: SPRING_LIQUIBASE_URL
    value: jdbc:postgresql://umbrella-chart-postgresql:5432/bank
  - name: KEYCLOAK_URL
    value: http://umbrella-chart-keycloak:8080
