services:
  front:
    container_name: front
    build: front
    ports:
      - '8085:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/bank-app
      ACCOUNT_SERVICE_URL: http://account:8080


  account:
    container_name: account
    build: account
    ports:
      - '8090:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://postgres:5432/bank-app

  gateway:
    container_name: gateway
    build: gateway
    ports:
      - '8081:8080'  # точка входа для всех внешних запросов
    depends_on:
      - front
      - account
    environment:
      ACCOUNT_SERVICE_URL: http://account:8080
      FRONT_SERVICE_URL: http://front:8080
      KEYCLOAK_URL: http://keycloak:8080/realms/bankapp
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bank-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false
    ports:
      - "8087:8080"
    depends_on:
      - keycloak-db
    volumes:
      - .keycloak/realm-export.json:/tmp/realm-export.json:ro

    keycloak-db:
      image: postgres:16
      container_name: keycloak-db
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak
      volumes:
        - keycloak-data:/var/lib/postgresql/data


volumes:
  pgdata:
  keycloak-data: