rootProject.name = "bank-app"
include("front")
include("account")
include("gateway")
include("cash")
include("notifications")
include("transfer")
include("exchange")
include("exchange-generator")
include("blocker")
