spring:
  application:
    name: transfer

client:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://account:8080}

server:
  port: 8083


management:
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always