spring:
  application:
    name: front
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank-app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        default_schema: front_schema
    liquibase:
      default-schema: fron
      enabled: true
#  cloud:
#    consul:
#      host: consul
#      port: 8500


client:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://account:8080}
  cash:
    url: ${CASH_SERVICE_URL:http://cash:8080}
  transfer:
    url: ${TRANSFER_SERVICE_URL:http://trasnfer:8080}
  exchange:
    url: ${EXCHANGE_SERVICE_URL:http://exchange:8080}

server:
  forward-headers-strategy: framework
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
