replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.1.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

readinessProbe:
  httpGet:
    path: /health/ready
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /health/live
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start-dev"
  - "--http-enabled=true"
  - "--hostname-strict=false"
  - "--import-realm"

env:
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: "admin"
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: "admin"

volumeMounts:
  - name: realm-import-volume
    mountPath: /opt/keycloak/data/import
    # монтируем директорию, а не файл
volumes:
  - name: realm-import-volume
    configMap:
      name: keycloak-realm-import-config-map

serviceAccount:
  create: true
  name: ""
