CREATE TABLE users (
 id BIGSERIAL PRIMARY KEY,
 login VARCHAR NOT NULL,
 name VARCHAR NOT NULL,
 birthdate DATE NOT NULL
);

CREATE TABLE accounts (
    id SERIAL PRIMARY KEY,
    currency VARCHAR(50) NOT NULL,
    value NUMERIC(19, 4) NOT NULL,
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);