spring:
  application:
    name: cash
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
#  cloud:
#    consul:
#      host: consul
#      port: 8500

server:
  port: 8095

client:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://account:8080}
  notifications:
    url: ${NOTIFICATIONS_SERVICE_URL:http://notifications:8080}

management:
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always