spring:
  application:
  name: cash
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank-app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

server:
  port: 8088

client:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://account:8080}
