- job_name: 'account'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['bank-app-umbrella-account:8090']

- job_name: 'exchange'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['bank-app-umbrella-exchange:8086']

- job_name: 'exchange-generator'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['bank-app-umbrella-exchange-generator:8088']

- job_name: 'front'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['bank-app-umbrella-front:8085']

- job_name: 'gateway'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['bank-app-umbrella-gateway:8081']

- job_name: 'keycloak'
  metrics_path: /actuator/prometheus
  static_configs:
    - targets: ['bank-app-umbrella-keycloak:8080']

- job_name: 'kafka'
  metrics_path: /metrics
  static_configs:
    - targets: ['bank-app-umbrella-kafka:9092']

