services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [ "start-dev", "--import-realm" ]
    ports:
      - "8087:8080"
    volumes:
      - ./realms/realm-export.json:/opt/keycloak/data/import/realm-export.json

networks:
  keycloak-net:
    driver: bridge