replicaCount: 1

image:
  repository: exchange-generator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8088

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8088
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8088
  initialDelaySeconds: 10
  periodSeconds: 5

serviceAccount:
  create: false
  name: default
  automount: false