global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'account'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bank-app-umbrella-account:8090']
        labels:
          application: 'account'

  - job_name: 'exchange'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bank-app-umbrella-exchange:8086']
        labels:
          application: 'exchange'

  - job_name: 'exchange-generator'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bank-app-umbrella-exchange-generator:8088']
        labels:
          application: 'exchange-generator'

  - job_name: 'front'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bank-app-umbrella-front:8085']
        labels:
          application: 'front'

  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bank-app-umbrella-gateway:8081']
        labels:
          application: 'gateway'

  - job_name: 'kafka'
    static_configs:
      - targets: ['bank-app-umbrella-kafka:9092']
        labels:
          application: 'kafka'

  - job_name: 'keycloak'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bank-app-umbrella-keycloak:8080']
        labels:
          application: 'keycloak'

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['bank-app-umbrella-kube-state-metrics:8080']
        labels:
          application: 'kube-state-metrics'

  - job_name: 'prometheus-node-exporter'
    static_configs:
      - targets: ['bank-app-umbrella-prometheus-node-exporter:9100']
        labels:
          application: 'node-exporter'

  - job_name: 'prometheus-pushgateway'
    static_configs:
      - targets: ['bank-app-umbrella-prometheus-pushgateway:9091']
        labels:
          application: 'pushgateway'

  - job_name: 'prometheus-server'
    static_configs:
      - targets: ['bank-app-umbrella-prometheus-server:80']
        labels:
          application: 'prometheus-server'

  - job_name: 'zipkin'
    static_configs:
      - targets: ['bank-app-umbrella-zipkin:9411']
        labels:
          application: 'zipkin'
