pipeline {
    agent any

    environment {
        SERVICE_NAME = "account"
        IMAGE_NAME = "bank-app/${SERVICE_NAME}"
        DOCKER_REGISTRY = "localhost:5000" // Можно поменять на свой registry
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'file:///Users/rvsemenov/IdeaProjects/bank-app', branch: 'feature/version-2'
            }
        }

        stage('Build') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Test') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit "${SERVICE_NAME}/build/test-results/test/*.xml"
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir("${SERVICE_NAME}") {
                    sh "docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest ."
                }
            }
        }

        stage('Docker Push') {
            steps {
                sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
            }
        }
    }

    post {
        always {
            echo "Pipeline for ${SERVICE_NAME} finished."
        }
    }
}
