replicaCount: 1

image:
  repository: gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

#initContainers:
#  - name: wait-for-keycloak
#    image: curlimages/curl:8.6.0
#    command: ["sh", "-c", "until curl -sf http://bank-umbrella-keycloak:8080/realms/bankapp/.well-known/openid-configuration; do echo waiting for keycloak; sleep 5; done"]

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false

env:
  - name: KEYCLOAK_URL
    value: "http://bank-keycloak:8080/realms/bankapp"
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: "http://bank-keycloak:8080/realms/bankapp"
  - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
    value: "http://bank-keycloak:8080/realms/bankapp"
