replicaCount: 1

image:
  repository: transfer
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false

autoscaling:
  enabled: false

resources: {}

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8083
  initialDelaySeconds: 30
  periodSeconds: 20

serviceAccount:
  create: false
  name: default
  automount: false